# Generated by Django 2.0 on 2017-12-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dice_description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('mote_cost', models.SmallIntegerField(blank=True)),
                ('willpower_cost', models.SmallIntegerField(blank=True)),
                ('anima_cost', models.SmallIntegerField(blank=True)),
                ('bashing_cost', models.SmallIntegerField(blank=True)),
                ('lethal_cost', models.SmallIntegerField(blank=True)),
            ],
        ),
    ]
