# Generated by Django 2.0 on 2017-12-10 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dice_description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('mote_cost', models.SmallIntegerField(blank=True)),
                ('willpower_cost', models.SmallIntegerField(blank=True)),
                ('anima_cost', models.SmallIntegerField(blank=True)),
                ('bashing_cost', models.SmallIntegerField(blank=True)),
                ('lethal_cost', models.SmallIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='charm',
            name='selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculator.Selection'),
        ),
    ]
