# Generated by Django 2.0 on 2017-12-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='value',
        ),
    ]
