# Generated by Django 2.0 on 2017-12-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_remove_selection_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charm',
            name='anima_cost',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='charm',
            name='bashing_cost',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='charm',
            name='lethal_cost',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='charm',
            name='mote_cost',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='charm',
            name='willpower_cost',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
