# Generated by Django 2.0 on 2017-12-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_charm_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='charm',
            name='charm_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='charm',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='charm',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
