# Generated by Django 2.0 on 2017-12-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_auto_20171210_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='charm',
            name='initiative_cost',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
