# Generated by Django 2.0 on 2017-12-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_charm_initiative_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='charm',
            name='ability',
            field=models.CharField(choices=[('brawl', 'BRAWL'), ('athletics', 'ATHLETICS'), ('occult', 'OCCULT'), ('resistance', 'RESISTANCE'), ('evocations', 'EVOCATIONS')], default='brawl', max_length=20),
        ),
    ]
