# Generated by Django 2.0 on 2017-12-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_charm_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charm',
            name='charm_type',
            field=models.CharField(choices=[('Simple', 'SIMPLE'), ('Supplemental', 'SUPPLEMENTAL'), ('Reflexive', 'REFLEXIVE'), ('Permanent', 'PERMANENT')], default='Reflexive', max_length=20),
        ),
        migrations.AlterField(
            model_name='charm',
            name='dice_description',
            field=models.TextField(default='t', null=True),
        ),
    ]
