# Generated by Django 2.0 on 2017-12-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_auto_20171212_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charm',
            name='dice_description',
            field=models.TextField(blank=True, default='t'),
        ),
    ]
