# Generated by Django 2.0 on 2017-12-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_auto_20171212_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='name',
            field=models.CharField(default='Selection', max_length=10),
            preserve_default=False,
        ),
    ]
